### ISSUE TITLE
Restart dyno policy

### ISSUE THREAD

**Issue by timkurvers** [hyperoslo/heroku-deploy#1]
On behalf of @sindrenm:

We should investigate how we would like dynos to behave after a deployment. The current Rails deploy pack restarts all dynos after migration to ensure all dynos are operating on the latest database schema. Some dynos might be independent of the database schema and thus could benefit from not being restarted.

**Comment by zenangst** [comment]
![depositphotos_21867439-stock-illustration-tyranosaurus-rex](https://user-images.githubusercontent.com/57446/117119531-80a41700-ad92-11eb-8750-4e782028e55a.jpg)
