### ISSUE TITLE
Allow deployment to accept input

### ISSUE THREAD

**Issue by sindrenm** [hyperoslo/heroku-deploy#20]
When doing the first `git push` to Heroku, Git will ask for the following user input:

> Are you sure you want to continue connecting (yes/no)?

This will not work with `heroku deploy`, as it doesn't accept any user input, and thus just hangs there, which is a teensy bit confusing.

**Comment by timkurvers** [comment]
Good catch! :+1:

**Comment by sindrenm** [comment]
Myes.
